# Generated by Django 3.0.7 on 2020-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=30)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_aadhar', models.IntegerField()),
                ('patient_complaint', models.TextField()),
            ],
        ),
    ]
