# Generated by Django 3.0.7 on 2020-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_aadhar', models.IntegerField()),
                ('patient_image', models.ImageField(upload_to='user/')),
                ('Patient_password', models.CharField(max_length=30)),
            ],
        ),
    ]
